# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-16 16:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userinformation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinformations',
            name='phone',
        ),
    ]
