# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-01 17:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userinformation', '0003_userinformations_access_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinformations',
            name='facebook',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userinformations',
            name='google',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userinformations',
            name='linkedIn',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userinformations',
            name='picture',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='userinformations',
            name='twitter',
            field=models.BooleanField(default=False),
        ),
    ]
