# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-10 05:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userinformation', '0004_auto_20170501_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinformations',
            name='github',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userinformations',
            name='social_id',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
