# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-10 18:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userinformation', '0005_auto_20170510_0545'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinformations',
            name='social_id',
        ),
    ]
